#!/bin/sh

INITRD=/system/boot/android-ramdisk.img
rm -Rf /tmp/android/
mkdir -p /tmp/android/
cd /tmp/android/
cat $INITRD | gzip -d | cpio -i

fstab=/tmp/android/fstab*

cat ${fstab} | while read line; do
    set -- $line
    # Skip any unwanted entry
    echo $1 | egrep -q "^#" && continue
    ([ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] || [ -z "$4" ]) && continue
    ([ "$3" = "emmc" ] || [ "$3" = "swap" ] || [ "$3" = "mtd" ]) && continue
    ([ "$2" = "/system" ] || [ "$2" = "/data" ]) && continue

    label=$(echo $1 | awk -F/ '{print $NF}')
    [ -z "$label" ] && continue

    # In case fstab provides /dev/mmcblk0p* lines
    path="/dev/$label"
    for dir in by-partlabel by-name by-label by-path by-uuid by-partuuid by-id; do
        if [ -e "/dev/disk/$dir/$label" ]; then
            path="/dev/disk/$dir/$label"
            break
        fi
    done

    [ ! -e "$path" ] && continue

    mkdir -p $2
    mount $path $2 -t $3 -o $4

done

# check if vendor is mounted/created? otherwise link it to system
[ -e "/vendor" ] || ln -s /system/vendor /vendor
